# The 7 fixtures were generated by an INDEPENDENT Python implementation of the
# governed-CSV spec (see the design zip's README). Reading them in R therefore
# tests that the R reader agrees with a second implementation, which an R-only
# round trip cannot do. These are ported from the prototype's
# demo_read_test_data.R.

fx <- function(name) test_path("fixtures", name)

test_that("a never-governed CSV reads as plain data, no metadata", {
  raw <- read_stable_csv(fx("raw_data.csv"))
  expect_equal(nrow(raw$data), 15)
  expect_length(raw$meta, 0)
})

test_that("a normal governed file reconstructs every payload cleanly", {
  v1 <- read_stable_csv(fx("governed_v1.csv"))
  expect_equal(nrow(v1$data), 15)
  expect_length(v1$missing, 0)
  expect_length(v1$mismatch, 0)
  expect_true(isTRUE(v1$stamp_consistent))
  expect_setequal(names(v1$meta), c("provenance", "renv", "factor_levels"))
})

test_that("lineage chains: v2 start_hash matches v1 current_hash", {
  v1 <- read_stable_csv(fx("governed_v1.csv"))
  v2 <- read_stable_csv(fx("governed_v2.csv"))
  expect_equal(v1$meta$provenance$current_hash$elapsed_days,
               v2$meta$provenance$start_hash$elapsed_days)
})

test_that("a single dropped carrier row still fully recovers (redundancy)", {
  # 2x replication spread far apart: losing one row costs nothing.
  single <- read_stable_csv(fx("governed_v1_corrupted_singledrop.csv"))
  expect_equal(nrow(single$data), 14)          # one data row genuinely gone
  expect_length(single$missing, 0)             # but every payload survives
  expect_setequal(names(single$meta), c("provenance", "renv", "factor_levels"))
})

test_that("both copies dropped is flagged missing, not silently absent", {
  # The one failure mode that fails SILENTLY if the manifest logic regresses:
  # without the manifest, total loss of a payload looks like it never existed.
  both <- read_stable_csv(fx("governed_v1_corrupted_bothcopies.csv"))
  expect_true("factor_levels" %in% both$missing)
  expect_setequal(names(both$meta), c("provenance", "renv"))  # others unaffected
})

test_that("tampering is flagged mismatch, distinct from data loss", {
  # No rows dropped; one copy edited to disagree with its twin. Data intact,
  # payload still reconstructs best-effort, but flagged for review.
  tamper <- read_stable_csv(fx("governed_v1_corrupted_tamper.csv"))
  expect_equal(nrow(tamper$data), 15)
  expect_true("factor_levels" %in% tamper$mismatch)
})

test_that("overflow rows compose correctly with replication", {
  # Payload inflated (tiny chunk limit + 3x replication) so items >> rows,
  # forcing appended overflow rows. Real data rows must stay separable.
  ov <- read_stable_csv(fx("governed_v1_overflow_demo.csv"))
  expect_equal(nrow(ov$data), 15)
  expect_length(ov$missing, 0)
})
