# Governed CSV: metadata embedded in the data file itself, so provenance
# travels with the CSV and there is no sidecar to lose (the ArcGIS-vs-sf
# lesson from the design discussion).
#
# Two tiers:
#
#   TIER 1  core stamp (.dgf_stamp) - a small JSON blob written IDENTICALLY on
#           every data row: dgf_version, a whole-file hash summary, created
#           timestamp, immediate lineage parent, and a payload manifest. Cheap
#           enough to survive any drop short of deleting nearly the whole file.
#
#   TIER 2  full payloads (.dgf_meta) - arbitrary named payloads (provenance,
#           renv, factor_levels, ...), chunked, and each independently
#           REPLICATED (default 2x) with copies spread far apart so a contiguous
#           drop (a filter, a head(n), a date subset) can't take out every copy.
#
# Placement: one item per row where possible (spread via probing); if items
# exceed rows, pack multiple per cell (Unit-Separator delimited); only then
# spill to appended overflow rows flagged .dgf_is_data = FALSE.
#
# Reading distinguishes two failure signatures:
#   missing  - every copy of a chunk is gone (real data loss)
#   mismatch - surviving copies disagree (possible tampering; best-effort value
#              still returned, flagged for review)
#
# This file is the wire format. The fixtures in tests/testthat/fixtures/ were
# generated by an independent Python implementation of this same spec, so they
# are the regression test - do not change a constant here without re-checking
# them. The user-facing API (write_stable_csv / read_stable_csv) wraps this.

DGF_SENTINEL         <- "##DGF##"
DGF_META_COL         <- ".dgf_meta"
DGF_STAMP_COL        <- ".dgf_stamp"
DGF_IS_DATA_COL      <- ".dgf_is_data"
DGF_CHUNK_CHAR_LIMIT <- 25000L   # Excel-safe per-chunk size
DGF_ITEM_SEP         <- "\x1f"   # ASCII Unit Separator: packs multiple chunk
                                  # items into one cell. Machine-only, not
                                  # meant to be read like the sentinel.
DGF_REPLICATION_DEFAULT <- 2L


#' Split a JSON string into fixed-size chunk pieces (internal)
#'
#' @param json_string A serialized payload.
#' @param limit Max characters per chunk.
#' @return A character vector of pieces, each `<= limit` long.
#' @noRd
.dgf_chunk_json <- function(json_string, limit = DGF_CHUNK_CHAR_LIMIT) {
  n_chunks <- max(1L, ceiling(nchar(json_string) / limit))
  starts <- seq(1, nchar(json_string), by = limit)
  vapply(seq_along(starts), function(i) {
    substr(json_string, starts[i], min(starts[i] + limit - 1, nchar(json_string)))
  }, character(1))
}


#' Compress a named list of hashes into one summary token (internal)
#'
#' @param lst A named list of hash strings.
#' @return An 8-hex-digit summary token.
#'
#' @details A tiny multiply-shift hash, used only to fold `current_hash` into a
#'   single value for the tier-1 stamp; the full detail still lives in the
#'   provenance payload. Kept dependency-free (no `digest`) for the prototype.
#'
#'   Two things this MUST get right, both of which the prototype got wrong:
#'   `%%` binds tighter than `*` in R, so the modulus is parenthesised to run
#'   after the multiply; and `sprintf("%08x", ...)` needs an integer, so the
#'   result is coerced with `as.integer()` before formatting.
#' @noRd
digest_list <- function(lst) {
  s <- paste(names(lst), unlist(lst), collapse = "|")
  sprintf("%08x", as.integer((sum(utf8ToInt(s)) * 2654435761) %% (2^31)))
}


#' Write a governed CSV (internal engine)
#'
#' The low-level writer: takes already-assembled payloads and embeds them.
#' [write_stable_csv()] is the user-facing wrapper.
#'
#' @param df Data frame to write (already standardized).
#' @param path Output file path.
#' @param payloads Named list of R objects to serialize, e.g.
#'   `list(provenance = list(...), renv = list(...))`.
#' @param core_stamp Small named list written on every row, unchunked and
#'   unreplicated. If `NULL` and a `provenance` payload is present, a minimal
#'   stamp is derived from it.
#' @param replication Named list of per-payload replication factors; payloads
#'   not named default to `DGF_REPLICATION_DEFAULT`.
#' @param chunk_limit Max characters per chunk.
#'
#' @return Invisibly, `path`.
#' @noRd
write_governed_csv <- function(df, path, payloads, core_stamp = NULL,
                                replication = list(),
                                chunk_limit = DGF_CHUNK_CHAR_LIMIT) {

  stopifnot(is.list(payloads), !is.null(names(payloads)))
  n_data <- nrow(df)

  # --- Tier 1: core stamp, identical on every row -----------------------
  if (is.null(core_stamp) && "provenance" %in% names(payloads)) {
    prov <- payloads[["provenance"]]
    core_stamp <- list(
      dgf_version = prov$dgf_version,
      created     = prov$created,
      current_hash_summary = if (!is.null(prov$current_hash))
        substr(digest_list(prov$current_hash), 1, 12) else NA,
      lineage_parent = if (length(prov$lineage) > 0) prov$lineage[[1]] else NULL
    )
  }

  # --- Tier 2: chunk + replicate each payload -----------------------------
  rep_for <- function(nm) {
    if (!is.null(replication[[nm]])) replication[[nm]] else DGF_REPLICATION_DEFAULT
  }

  # Payload MANIFEST: names + chunk/copy counts, folded into the core stamp.
  # This is what makes TOTAL loss of a payload detectable -- without it, a
  # payload whose every chunk/copy is gone is silently indistinguishable from a
  # file that never had it. The manifest survives as long as even one data row
  # does, since the stamp is written identically on every row.
  manifest <- list()

  items <- list()  # each: list(payload=, copy=, seq=, total=, body=, preferred_row=)
  for (nm in names(payloads)) {
    json <- as.character(jsonlite::toJSON(payloads[[nm]], auto_unbox = TRUE))
    pieces <- .dgf_chunk_json(json, chunk_limit)
    k <- length(pieces)
    r <- rep_for(nm)
    manifest[[nm]] <- list(chunks = k, copies = r)
    for (copy in seq_len(r)) {
      start <- if (n_data > 0) floor((copy - 1) * n_data / r) else 0
      for (seq_i in seq_len(k)) {
        items[[length(items) + 1]] <- list(
          payload = nm, copy = copy, seq = seq_i, total = k,
          body = pieces[seq_i],
          preferred_row = if (n_data > 0) ((start + seq_i - 1) %% n_data) + 1 else NA
        )
      }
    }
  }

  core_stamp$payload_manifest <- manifest
  stamp_json <- as.character(jsonlite::toJSON(core_stamp, auto_unbox = TRUE))

  item_strings <- vapply(items, function(it)
    paste(it$payload, it$copy, it$seq, it$total, it$body, sep = "|"), character(1))
  item_preferred_row <- vapply(items, function(it) it$preferred_row, numeric(1))

  out <- df
  out[[DGF_STAMP_COL]] <- if (n_data > 0) rep(stamp_json, n_data) else character(0)
  out[[DGF_META_COL]] <- NA_character_

  row_bucket <- vector("list", max(n_data, 1))
  row_bucket_len <- rep(0L, max(n_data, 1))
  overflow_items <- character(0)

  if (n_data > 0 && length(item_strings) > 0) {
    # Pass 1: place one item per row via linear probing from its preferred
    # (spread) row, so redundant copies land far apart.
    used <- rep(FALSE, n_data)
    unplaced <- integer(0)
    for (i in seq_along(item_strings)) {
      pref <- item_preferred_row[i]
      placed <- FALSE
      for (offset in 0:(n_data - 1)) {
        r <- ((pref - 1 + offset) %% n_data) + 1
        if (!used[r]) {
          row_bucket[[r]] <- item_strings[i]
          row_bucket_len[r] <- nchar(item_strings[i])
          used[r] <- TRUE
          placed <- TRUE
          break
        }
      }
      if (!placed) unplaced <- c(unplaced, i)
    }

    # Pass 2: pack any unplaced items into existing rows (round-robin),
    # respecting the per-cell char cap.
    if (length(unplaced) > 0) {
      ptr <- 1
      still_unplaced <- integer(0)
      for (i in unplaced) {
        placed <- FALSE
        for (tries in seq_len(n_data)) {
          r <- ((ptr - 1) %% n_data) + 1
          ptr <- ptr + 1
          new_len <- row_bucket_len[r] + nchar(DGF_ITEM_SEP) + nchar(item_strings[i])
          if (new_len <= chunk_limit) {
            row_bucket[[r]] <- if (row_bucket_len[r] == 0) item_strings[i]
                                 else paste(row_bucket[[r]], item_strings[i], sep = DGF_ITEM_SEP)
            row_bucket_len[r] <- new_len
            placed <- TRUE
            break
          }
        }
        if (!placed) still_unplaced <- c(still_unplaced, i)
      }
      # Pass 3: whatever still doesn't fit becomes overflow footer rows.
      if (length(still_unplaced) > 0) {
        overflow_items <- item_strings[still_unplaced]
      }
    }

    for (r in seq_len(n_data)) {
      if (row_bucket_len[r] > 0) out[[DGF_META_COL]][r] <- row_bucket[[r]]
    }
  } else if (length(item_strings) > 0) {
    overflow_items <- item_strings
  }

  if (length(overflow_items) > 0) {
    out[[DGF_IS_DATA_COL]] <- TRUE
    overflow_block <- as.data.frame(
      matrix(NA_character_, nrow = length(overflow_items), ncol = ncol(out)),
      stringsAsFactors = FALSE
    )
    names(overflow_block) <- names(out)
    overflow_block[[1]] <- DGF_SENTINEL
    overflow_block[[DGF_META_COL]] <- overflow_items
    overflow_block[[DGF_STAMP_COL]] <- NA_character_
    overflow_block[[DGF_IS_DATA_COL]] <- FALSE
    out <- rbind(out, overflow_block[names(out)])
  }

  utils::write.csv(out, path, row.names = FALSE, na = "")
  invisible(path)
}


#' Read a governed CSV (internal engine)
#'
#' @param path Path to a governed CSV.
#' @return A list: `data`, reassembled `stamp`, `stamp_consistent`, `meta`
#'   (tier-2 payloads), and `missing` / `mismatch` failure signatures.
#' @noRd
read_governed_csv <- function(path) {

  raw <- utils::read.csv(path, colClasses = "character",
                          check.names = FALSE, na.strings = "")

  if (!(DGF_META_COL %in% names(raw))) {
    return(list(data = raw, stamp = NULL, stamp_consistent = NA,
                meta = list(), missing = character(0), mismatch = character(0)))
  }

  has_flag <- DGF_IS_DATA_COL %in% names(raw)
  is_data <- if (has_flag) raw[[DGF_IS_DATA_COL]] == "TRUE" else rep(TRUE, nrow(raw))

  drop_cols <- intersect(c(DGF_META_COL, DGF_STAMP_COL, DGF_IS_DATA_COL), names(raw))
  data <- raw[is_data, setdiff(names(raw), drop_cols), drop = FALSE]

  # --- Tier 1: core stamp -------------------------------------------------
  stamp <- NULL; stamp_consistent <- NA
  if (DGF_STAMP_COL %in% names(raw)) {
    stamps <- raw[[DGF_STAMP_COL]][!is.na(raw[[DGF_STAMP_COL]])]
    if (length(stamps) > 0) {
      tab <- table(stamps)
      majority <- names(tab)[which.max(tab)]
      stamp_consistent <- length(unique(stamps)) == 1
      stamp <- tryCatch(jsonlite::fromJSON(majority), error = function(e) NULL)
    }
  }

  # --- Tier 2: payloads, un-packing multi-item cells first ----------------
  meta_vals <- raw[[DGF_META_COL]][!is.na(raw[[DGF_META_COL]])]
  all_items <- unlist(strsplit(meta_vals, DGF_ITEM_SEP, fixed = TRUE))

  meta <- list(); missing <- character(0); mismatch <- character(0)

  if (length(all_items) > 0) {
    parts <- strsplit(all_items, "|", fixed = TRUE)
    chunks <- data.frame(
      payload = vapply(parts, `[`, "", 1),
      copy    = vapply(parts, `[`, "", 2),
      seq     = as.integer(vapply(parts, `[`, "", 3)),
      total   = as.integer(vapply(parts, `[`, "", 4)),
      body    = vapply(parts, function(p) paste(p[-(1:4)], collapse = "|"), ""),
      stringsAsFactors = FALSE
    )

    for (pl in unique(chunks$payload)) {
      sub <- chunks[chunks$payload == pl, ]
      total_tab <- table(sub$total)
      expected <- as.integer(names(total_tab)[which.max(total_tab)])

      body_parts <- character(expected)
      pl_missing <- FALSE
      pl_mismatch <- FALSE

      for (s in seq_len(expected)) {
        candidates <- unique(sub$body[sub$seq == s])
        if (length(candidates) == 0) {
          pl_missing <- TRUE
          break
        }
        if (length(candidates) > 1) pl_mismatch <- TRUE
        body_parts[s] <- candidates[1]  # best-effort: first surviving copy
      }

      if (pl_missing) {
        missing <- c(missing, pl)
        next
      }
      if (pl_mismatch) mismatch <- c(mismatch, pl)

      meta[[pl]] <- tryCatch(
        jsonlite::fromJSON(paste(body_parts, collapse = "")),
        error = function(e) { missing <<- c(missing, pl); NULL }
      )
    }
  }

  # Cross-check against the manifest: catches TOTAL loss of a payload (every
  # chunk/copy gone), otherwise silently indistinguishable from a payload that
  # never existed since there are zero surviving chunks to notice as incomplete.
  if (!is.null(stamp) && !is.null(stamp$payload_manifest)) {
    expected_payloads <- names(stamp$payload_manifest)
    fully_absent <- setdiff(expected_payloads, c(names(meta), missing))
    missing <- union(missing, fully_absent)
  }

  list(data = data, stamp = stamp, stamp_consistent = stamp_consistent,
       meta = meta, missing = missing, mismatch = mismatch)
}


# write_stable_csv() lives in R/09-stabilize-data.R, where it also gains the
# DGF-aware `dgf=`/`start_hash=` arguments. It calls write_governed_csv() above.


#' Read a stable CSV, recovering data and embedded provenance
#'
#' Reads a CSV written by [write_stable_csv()], returning the data plus the
#' embedded metadata, and flagging two distinct integrity problems.
#'
#' @param path Path to a stable CSV. A plain, never-governed CSV is read too -
#'   it just returns empty metadata.
#'
#' @return A list with:
#'   \describe{
#'     \item{`data`}{the data frame, with metadata columns removed}
#'     \item{`stamp`}{the tier-1 core stamp (version, hash summary, manifest)}
#'     \item{`stamp_consistent`}{`TRUE` if every row's stamp agreed}
#'     \item{`meta`}{the recovered payloads, named}
#'     \item{`missing`}{payloads every copy of which is gone (data loss)}
#'     \item{`mismatch`}{payloads whose surviving copies disagree (possible
#'       tampering; a best-effort value is still returned)}
#'   }
#'
#' @seealso [write_stable_csv()]
#' @export
read_stable_csv <- function(path) {
  read_governed_csv(path)
}
